services:
  client:
    container_name: client
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    build: .
    environment:
      NODE_ENV: ${NODE_ENV}
      REACT_APP_HOST: ${REACT_APP_HOST}
    networks:
      - bpi_default
    command: sh -c "npm i && npx tailwindcss -i ./src/index.css -o ./src/build.css && npm run build"

  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - bpi_default
    ports:
      - "80:80"
      - "443:443"
    command: 'nginx -g "daemon off;"'

networks:
  bpi_default:
    name: bpi_default
