name: Deployment process
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build process
    runs-on: ubuntu-latest
    steps:
      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd client
            git fetch origin master
            git reset --hard FETCH_HEAD
            sudo npm i
            sudo npx tailwindcss -i ./src/index.css -o ./src/build.css
            sudo npm run build
